version: '3.8'

services:
  bonpreu-scraper:
    build: .
    container_name: bonpreu-scraper
    volumes:
      - .:/app
      - bonpreu-db:/app/db
    environment:
      - DISPLAY=:99
      - Bonpreu_PASSWORD=${Bonpreu_PASSWORD}
    command: python3 /app/order.py

volumes:
  bonpreu-db:
    external: true

